### ISSUE TITLE
Close methods for tab pages

### ISSUE THREAD

**Issue by kristol07** [SZ559/Well-Trajectory-Visualization-GUI-#27]
Closing one tab page should be more effective.

**Comment by SZ559** [comment]
https://blog.csdn.net/u013944260/article/details/76720853

**Comment by SZ559** [comment]
https://blog.csdn.net/a4600646/article/details/101816271?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-7.nonecase&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-7.nonecase

**Comment by SZ559** [comment]
drawitem event
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tabcontrol.drawitem?view=netcore-3.1
