### ISSUE TITLE
Axis problems

### ISSUE THREAD

**Issue by kristol07** [SZ559/Well-Trajectory-Visualization-GUI-#46]
- the axis saved in picture vs that in app are different
- when numbers in axis are too large, it will become multi-lined

**Comment by SZ559** [comment]
This one has no problem

**Comment by kristol07** [comment]
> 
> 
>     * the axis saved in picture vs that in app are different
> 
>     * when numbers in axis are too large, it will become multi-lined

The first problem is not new bug but problem of merging.
The second could be solved by using scientific notation method.

**Comment by kristol07** [comment]
Problem of resolution for numbers after using scientific notion.
